### ISSUE TITLE
Consider Python-native mysql client library

### ISSUE THREAD

**Issue by mortoray** [pushcoin/mysqlripper#8]
This should simplify the install for users who don’t want to mess around with compiling anything and with the cross-platform support:

https://github.com/PyMySQL/PyMySQL

**Comment by mortoray** [comment]
@slisznia Do you know if this supports MariaDB?

If we assume that `mysqlclient` is installed, I could also call that via a shell and use the CSV output results instead. It's only one call made to the DB, to get the table sizes.

**Comment by slisznia** [comment]
Yes, it supports MariaDB. We should try the package ahead of using
mysql-client binary. Over time, our needs to run various queries as part of
running the tool may increase so having an easy way to make DB calls and
collect results is important.
